language: go

stages:
  - lint
  - test

go:
  - 1.12.x
  - tip

env: GO111MODULE=on
before_install: go get -u github.com/kyoh86/richgo
script:
  - richgo test -v ./...
  - go build

matrix:
  allow_failures:
    - go: tip
  include:
    - stage: lint
      go: 1.12.x
      before_install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
      script: golangci-lint run -v
