# Reference: https://github.com/CodelyTV/pr-size-labeler

name: size-labeler

on: [pull_request_target]

permissions:
  contents: read

jobs:
  size-labeler:
    permissions:
      pull-requests: write  # for codelytv/pr-size-labeler to add labels & comment on PRs
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1.8.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '24'
          m_label: 'size/M'
          m_max_size: '99'
          l_label: 'size/L'
          l_max_size: '200'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
          message_if_xl: >
            'This PR exceeds the recommended size of 200 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.â€™
